### ISSUE TITLE
Website inaccessible via https

### ISSUE THREAD

**Issue by emmatyping** [JukkaL/mypy-website#12]
When I try to navigate to https://mypy-lang.org/ it fails to load. I'm not sure how the website is hosted, but it appears to be self hosted. Perhaps using [Let's Encrypt](https://letsencrypt.org/getting-started/) would be a good solution?

**Comment by johnthagen** [comment]
For what it's worth, using HTTPS would also boost mypy-lang.org's ranking in Google searches: https://aboutssl.org/does-an-ssl-certificate-impact-google-rankings/

**Comment by gvanrossum** [comment]
I'd recommend switching to GitHub Pages.

**Comment by johnthagen** [comment]
It looks like mypy website is built using a mostly custom build/generation method.

One alternative would be something like Material for MkDocs, which is a full fledged static site generator, which allows you to write the site in Markdown: https://squidfunk.github.io/mkdocs-material/

There is support for publishing to directly to GitHub Pages from GitHub Actions built into MkDocs: https://squidfunk.github.io/mkdocs-material/publishing-your-site/#github-pages

**Comment by aphedges** [comment]
I just noticed that this is fixed. <https://mypy-lang.org/> now loads properly, and Firefox does not complain about the certificate.
